# Generated by Django 4.2.7 on 2024-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_shipmentstatus_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='batch',
            field=models.CharField(max_length=50),
        ),
    ]
