# Generated by Django 4.2.7 on 2024-12-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_shipmentstatus_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenthistory',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipmenthistory',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
