# Generated by Django 4.2.7 on 2024-12-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shipmenthistory_latitude_shipmenthistory_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenthistory',
            name='currentLocation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
