# Generated by Django 4.2.7 on 2024-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shipmentstatus_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
