# Generated by Django 4.2.7 on 2024-06-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippersFullname', models.CharField(max_length=200)),
                ('shippersAddress', models.CharField(default='', max_length=200)),
                ('shippersPhone', models.CharField(max_length=15)),
                ('shippersEmail', models.EmailField(max_length=254)),
                ('recieversFullname', models.CharField(max_length=200)),
                ('recieversAddress', models.CharField(default='', max_length=200)),
                ('recieversPhone', models.CharField(max_length=15)),
                ('recieversEmail', models.EmailField(max_length=254)),
                ('origin', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('typeOfShipment', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('shipmentMove', models.CharField(max_length=100)),
                ('carrierReferenceNo', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('expectedDeliveryDate', models.CharField(max_length=100)),
                ('departureTime', models.CharField(max_length=100)),
                ('pickUpDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='shipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('updatedBy', models.CharField(max_length=100)),
                ('carrierRefernceNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shipmentstatus')),
            ],
        ),
    ]
