# Generated by Django 4.2.7 on 2024-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenthistory',
            name='carrierRefernceNo',
        ),
        migrations.AddField(
            model_name='shipmenthistory',
            name='carrierReferenceNo',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmenthistory',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='carrierReferenceNo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
