# Generated by Django 4.2.7 on 2024-06-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shipmenthistory_carrierrefernceno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentstatus',
            old_name='package',
            new_name='batch',
        ),
        migrations.RemoveField(
            model_name='shipmentstatus',
            name='shipmentMove',
        ),
    ]
