# Generated by Django 4.2.7 on 2024-06-23 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shipmenthistory_carrierreferenceno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstatus',
            name='receivedDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
